 const Tag = require("../models/tag");

let tags = [
  { name: "Hiking", group_id: 1 },
  { name: "Outdoor Adventures", group_id: 1 },
  { name: "Nature Exploration", group_id: 1 },
  { name: "Photography", group_id: 2 },
  { name: "Landscape", group_id: 2 },
  { name: "Portraits", group_id: 2 },
  { name: "Cooking", group_id: 3 },
  { name: "Gourmet Recipes", group_id: 3 },
  { name: "International Cuisine", group_id: 3 },
  { name: "Guitar", group_id: 4 },
  { name: "Acoustic", group_id: 4 },
  { name: "Electric", group_id: 4 },
  { name: "Writing", group_id: 5 },
  { name: "Fiction", group_id: 5 },
  { name: "Poetry", group_id: 5 },
  { name: "Art", group_id: 6 },
  { name: "Painting", group_id: 6 },
  { name: "Drawing", group_id: 6 },
  { name: "Fitness", group_id: 7 },
  { name: "Workout", group_id: 7 },
  { name: "Yoga", group_id: 7 },
  { name: "Book Club", group_id: 8 },
  { name: "Literature", group_id: 8 },
  { name: "Bestsellers", group_id: 8 },
  { name: "Yoga", group_id: 9 },
  { name: "Mindfulness", group_id: 9 },
  { name: "Wellness", group_id: 9 },
  { name: "Crafting", group_id: 10 },
  { name: "Knitting", group_id: 10 },
  { name: "Paper Crafts", group_id: 10 },
  { name: "Pottery", group_id: 11 },
  { name: "Ceramics", group_id: 11 },
  { name: "Clay Art", group_id: 11 },
  { name: "Chess", group_id: 12 },
  { name: "Strategy Games", group_id: 12 },
  { name: "Board Games", group_id: 12 },
  { name: "Films", group_id: 13 },
  { name: "Movies", group_id: 13 },
  { name: "Cinematography", group_id: 13 },
  { name: "Gardening", group_id: 14 },
  { name: "Urban Agriculture", group_id: 14 },
  { name: "Plants", group_id: 14 },
  { name: "Startups", group_id: 15 },
  { name: "Entrepreneurship", group_id: 15 },
  { name: "Innovation", group_id: 15 },
  { name: "Science Fiction", group_id: 16 },
  { name: "Fantasy", group_id: 16 },
  { name: "Speculative Fiction", group_id: 16 },
  { name: "Coffee", group_id: 17 },
  { name: "Espresso", group_id: 17 },
  { name: "Coffee Tasting", group_id: 17 },
  { name: "Meditation", group_id: 18 },
  { name: "Mindfulness", group_id: 18 },
  { name: "Wellness", group_id: 18 },
  { name: "Languages", group_id: 19 },
  { name: "Polyglot", group_id: 19 },
  { name: "Language Learning", group_id: 19 },
  { name: "Investing", group_id: 20 },
  { name: "Stocks", group_id: 20 },
  { name: "Finance", group_id: 20 },
  { name: "Dogs", group_id: 21 },
  { name: "Pets", group_id: 21 },
  { name: "Canines", group_id: 21 },
  { name: "Cosplay", group_id: 22 },
  { name: "Costume Design", group_id: 22 },
  { name: "Character Play", group_id: 22 },
  { name: "Cycling", group_id: 23 },
  { name: "Biking", group_id: 23 },
  { name: "Outdoor Activities", group_id: 23 },
  { name: "Cuisine", group_id: 24 },
  { name: "Cooking", group_id: 24 },
  { name: "Global Foods", group_id: 24 },
  { name: "Coding", group_id: 25 },
  { name: "Programming", group_id: 25 },
  { name: "Software Development", group_id: 25 },
  { name: "Vintage Cars", group_id: 26 },
  { name: "Classic Cars", group_id: 26 },
  { name: "Car Restoration", group_id: 26 },
  { name: "Home Brewing", group_id: 27 },
  { name: "Craft Beer", group_id: 27 },
  { name: "Brewing Techniques", group_id: 27 },
  { name: "Astronomy", group_id: 28 },
  { name: "Stargazing", group_id: 28 },
  { name: "Space Exploration", group_id: 28 },
  { name: "Poetry", group_id: 29 },
  { name: "Poetry Reading", group_id: 29 },
  { name: "Creative Writing", group_id: 29 },
  { name: "Robotics", group_id: 30 },
  { name: "AI", group_id: 30 },
  { name: "Machine Learning", group_id: 30 },
  { name: "Bird Watching", group_id: 31 },
  { name: "Ornithology", group_id: 31 },
  { name: "Nature", group_id: 31 },
  { name: "Gardening", group_id: 32 },
  { name: "Plant Care", group_id: 32 },
  { name: "Horticulture", group_id: 32 },
  { name: "DIY", group_id: 33 },
  { name: "Home Decor", group_id: 33 },
  { name: "Interior Design", group_id: 33 },
  { name: "Comedy", group_id: 34 },
  { name: "Stand-Up", group_id: 34 },
  { name: "Jokes", group_id: 34 },
  { name: "Fantasy Sports", group_id: 35 },
  { name: "Sports", group_id: 35 },
  { name: "Competition", group_id: 35 },
  { name: "History", group_id: 36 },
  { name: "Archaeology", group_id: 36 },
  { name: "Historical Events", group_id: 36 },
  { name: "Music Production", group_id: 37 },
  { name: "Sound Design", group_id: 37 },
  { name: "Mixing", group_id: 37 },
  { name: "Sustainability", group_id: 38 },
  { name: "Eco-Friendly", group_id: 38 },
  { name: "Zero Waste", group_id: 38 },
  { name: "Vegan Cooking", group_id: 39 },
  { name: "Plant-Based Diet", group_id: 39 },
  { name: "Vegan Nutrition", group_id: 39 },
  { name: "Chess", group_id: 40 },
  { name: "Strategy", group_id: 40 },
  { name: "Board Games", group_id: 40 },
];
const seedTags = async () => {
  try {
    await Tag.bulkCreate(tags);
    console.log("tags created");
  } catch (error) {
    console.error("tags not created", error);
  }
};
module.exports = seedTags;
